### ISSUE TITLE
Support GPX

### ISSUE THREAD

**Issue by mnalis** [rudokemper/google-maps-places-to-organic-maps#1]
Could we have support for [.gpx](https://en.wikipedia.org/wiki/GPS_Exchange_Format) output too, in addition to Google's .KMZ ?

**Comment by rudokemper** [comment]
Good catch! I see that Organic Maps now [supports GPX import](https://organicmaps.app/news/2023-06-07/gpx-import-is-now-supported-in-organic-maps/), so this request matches the use case of the project.

I'll put in some work later today.

**Comment by rudokemper** [comment]
Done: https://github.com/rudokemper/google-maps-places-to-organic-maps/commit/e9a5d7e3e0074ed23e62472666bc7cf0d7402398
